### PR TITLE
modify the logic about removing or adding slides dynamically

### PR DESCRIPTION
**Pull request by zhouqiangWang**
1. Disable slide (not autocycle) when theres only one image? #82 …
2. Modify PagerIndicator show wrong numbers of indicators when call removeSliderAt
3. modify ViewPager scroll logic when SliderAdapter data change.  avoid slide around a bunch on initializing after removing or adding slides dynamically

### CODE REVIEW

**Comment by zhouqiangWang** [comment]
please help to review this modification.
It fix some logic error about removing or adding slides dynamically.
And I add two menus in the demo to test it,

Actually, there is one more issue about sliding around a bunch sliders after  removing or adding dynamically. Now I just disable the smooth animation but it will display blank sometimes.
Do you have any sugguestion?

**Comment by daimajia** [comment]
@zhouqiangWang This pull request can not merge automatically, you need to pull the latest code, solve the conflict and then re-push it.

**Comment by zhouqiangWang** [comment]
conflict resolved.

**Comment by daimajia** [comment]
When there is only one image slider, it's still cycling.

**Comment by zhouqiangWang** [comment]
I tried it. unless you scroll some. triggered
https://github.com/daimajia/AndroidImageSlider/blob/master/library/src/main/java/com/daimajia/slider/library/SliderLayout.java#L193-L204
It will notbe cycling.

**Comment by daimajia** [comment]
@zhouqiangWang Still buggy:

- When removing slider, there will be a white blank area
- When there is only one image, it will still able to scroll.

**Pull request closed without merging**
