### PR TITLE
replace picasso library to universal image loader library

### PR DESCRIPTION
**Pull request by bkhezry**
this option only work with image url

### CODE REVIEW

**Comment by daimajia** [comment]
It's not a good idea to totally replace Picasso with Universal Image Loader,  cause there are lots of developers are using this library.

A good solution is support multiple image load method, for example, when I call a method named setImageLoadEngine(Engine.Picasso| Engine.ImageLoader), it uses the diffirent image load engine.

**Comment by bkhezry** [comment]
ok.
please remove this pull request, I will try do that :-)

**Comment by daimajia** [comment]
There is no need to close this PULL, every time you push your own code, it will be automatically sync here. :-D

**Comment by yinyinnie** [comment]
I agree that:  It's not a good idea to totally replace Picasso with Universal Image Loader, cause there are lots of developers are using this library.

A good solution is support multiple image load method, for example, when I call a method named setImageLoadEngine(Engine.Picasso| Engine.ImageLoader), it uses the diffirent image load engine.

**Pull request closed without merging**
