### PR TITLE
Exposed the PageChangeListener in the PageIndicator

### PR DESCRIPTION
**Pull request by massimobio**
This is the solutions indicated by @devflow in #42

### CODE REVIEW

**Comment by daimajia** [comment]
Actually there is a better solution on #42. Cause let user involk PagerIndicator.setOnPageChangeListener will make them not easy to understand what they are doing.

I think we can overide [`ViewPagerEx`.`setOnPageChangeListenrer` ](https://github.com/daimajia/AndroidImageSlider/blob/master/library/src/main/java/com/daimajia/slider/library/Tricks/ViewPagerEx.java#L591-L593), using an ArrayList to save all the listener, and call it sequentially .

**Comment by massimobio** [comment]
Sounds like a good idea. Thanks for looking into this.

**Comment by daimajia** [comment]
Any interesting to be a collaborator of this project?

**Comment by massimobio** [comment]
I just recently switched to Android Studio and Gradle and I've never worked on a stand-alone library like this so I probably wouldn't be much help, but thanks for asking.
I will spend some more time with this library and if I feel more comfortable I'll contact you.

**Comment by daimajia** [comment]
@massimobio Great! Feel free to contact me when you are ready!

**Comment by massimobio** [comment]
Could you point me to some documents or tutorials specifically for working with these kinds of libraries? I wasn't even able to get the demo app to compile correctly. I had to manually pull out the classes and drop them into my project. Gradle is great for using open source projects, but I'm still at a loss about how things work behind then scenes. I'm eager to learn so I can contribute.

**Comment by daimajia** [comment]
You can check this video to learn how to import GitHub project into Android Studio.
https://teamtreehouse.com/library/android-tools/git/pulling-down-github-projects-to-android-studio

Check this to learn how to make custom view.
- http://www.vogella.com/tutorials/AndroidCustomViews/article.html
- http://developer.android.com/training/custom-views/index.html

Check this to learn how to working with GitHub collaborators (Git workflow): 
- https://www.atlassian.com/git/tutorials/comparing-workflows/centralized-workflow

:-D Any problem or question feel free to comment here.

**Comment by massimobio** [comment]
Wonderful. Thank you very much.

**Comment by massimobio** [comment]
Hi, I added an ArrayList of listeners in the ViewPagerEx and it works, but there is an issue with the position number coming form the infinite view pager being a big number that needs to be converted to the correct position like you did in PageIndicator: 
`int n = position % mItemCount;`
I wouldn't want the user to have to do this, as he would expect a number between 0 and number of views, but I wasn't able to find out the number of slider views in the ViewPagerEx
`mAdapter.getCount()` does not return the number of items
`mExpectedAdapterCount` also is some large number 
Any suggestions?

**Comment by daimajia** [comment]
This may help you, check it. 
https://github.com/daimajia/AndroidImageSlider/blob/8c2e9c7c54b7255c40ca7c8f3ade7ff7026a1945/library/src/main/java/com/daimajia/slider/library/Tricks/InfinitePagerAdapter.java#L40-L42

**Pull request closed without merging**
