### PR TITLE
Disable slide (not autocycle) when theres only one image? #82

### PR DESCRIPTION
**Pull request by zhouqiangWang**
Disable slide (not autocycle) when theres only one image? #82

### CODE REVIEW

**Comment by daimajia** [comment]
A good PR.
But I think you have missed something.  
For example, user  call [removeSliderAt](https://github.com/daimajia/AndroidImageSlider/blob/master/library/src/main/java/com/daimajia/slider/library/SliderLayout.java#L624-L642) method to remove slider, when there is only one image, we need to disable cycling and disable scroll motion. and next call addslider method to recover the count of the slider (SliderCount > 1), we need to enable scroll motion and enable cycling action.

**Comment by zhouqiangWang** [comment]
Yes. I found some side effects in some other scenarios. And I have got the issue @jschleppy commented at #82 . I will try to fix it tonight.
>This, and the fact that simply removing and adding slides dynamically makes it freak out and slide around a bunch on initializing

**Comment by daimajia** [comment]
@zhouqiangWang  Great. Thanks for working on this PR.

**Comment by zhouqiangWang** [comment]
close this. I will request new one.

**Pull request closed without merging**
