### PR TITLE
Added a OnPageChangeListener to the SliderLayout

### PR DESCRIPTION
**Pull request by massimobio**
I implemented the ArrayList of listeners in ViewPagerEx as you recommended and used the item count in the InfinitePager to calculate the page number.
I also implemented the listener in the demo with a simple log.

### CODE REVIEW

**Comment by massimobio** [comment]
I made another small fix and the commit showed up here. 
I was going to do a separate pull requests but I guess I can only do one a the time and all my commits show up here. 
Thanks for being patient.

**Comment by zhouqiangWang** [comment]
hello, Mr Massimobio,
This is Zhouqiang Wang, I am curious about why you want add ArrayList of listeners in ViewPagerEx.
Because as the comments
>@author daimajia : I just remove the if condition in setPageTransformer() to make it compatiable with Android 2.0+

And I check the android source code of ViewPager at [androidxref](http://androidxref.com/5.1.0_r1/xref/frameworks/support/v4/java/android/support/v4/view/ViewPager.java). There is no ArrayList of listeners workflow in latest ViewPager.java.  
So could u help to add the reason in your comment?

**Comment by daimajia** [comment]
Great job! I think there also need a method to `removeListener(OnPageChangeListener listener)`, because if we start to use multiple listener design, we must need both remove and add method.

**Comment by daimajia** [comment]
@zhouqiangWang Please check this closed PR 's comment to know why we need an ArrayList to manage listener. https://github.com/daimajia/AndroidImageSlider/pull/98

**Comment by massimobio** [comment]
Yes makes sense, but how would a user know that behind the scenes we implemented the multiple listeners? 
Usually you would set the listener to null to remove it, but it wouldn't work in our case, so should we throw an exception with a helpful error message?

**Comment by daimajia** [comment]
@massimobio  I think the easiest way to make user know there is an arraylist managing their Listener is to change the name from  `setOnPageChangeListener` to `addOnPageChangeListener` just like Android's [`ViewTreeObserver`](http://developer.android.com/reference/android/view/ViewTreeObserver.html) class.

**Comment by massimobio** [comment]
Very good point. I updated my pull request.

**Comment by daimajia** [comment]
@massimobio One more thing, the method name `setOnPageChange` is not appropriate, cause set method always manipulate object variable, i think the best name should be `triggerOnPageChangeEvent`  just like Android always rules. https://developer.android.com/reference/android/hardware/TriggerEventListener.html

**Comment by massimobio** [comment]
Just boarding a long flight. Will take care of it tomorrow. Thank you for your insightful input. 
Question regarding comments: I see the ViewPagerEx has java doc formatted comments but SliderLayout not as much. Is that intentional?

**Comment by daimajia** [comment]
Have a good sleep. It's not very urgent. 
We should make any pull request to be perfect, because every line of your code will be seen by other developers, every line of your code may be affect millions users, especially when we are making a library. 

The ViewPagerEx is the source code of ViewPager actually. The comments are all added by google's developer. SliderLayout should have clear comments. This is an early library I made, I didn't think too much on this. It now seems not right.

**Comment by massimobio** [comment]
@daimajia I absolutely agree with you. Building a library is very much different that coding for your own app, and should follow widely agreed upon conventions as much as possible.

**Comment by daimajia** [comment]
@massimobio Great! Thanks for your working on this project. How about to be a collaborator of this project?

**Comment by massimobio** [comment]
@daimajia sure, if you think I can be helpful. I'll try my best. 
How do you decide when to bump the release version?
I see that the latest release in github is 1.0.9 while gradle is up to 1.1.2

**Comment by daimajia** [comment]
@massimobio 
Cool, I have added you to the list of collaborators. Welcome to join this project.

Actually the version is still 1.0.9, v1.1.2 is gradle version instead of the library version. https://github.com/daimajia/AndroidImageSlider/blob/master/library/build.gradle#L11 

I'll publish a new release this weekend. :-D

**Comment by massimobio** [comment]
Great, I'll answer and close the related issues to this pull. 
Interesting about Gradle version differing from the release version. So using the 1.1.2 Gradle dependency on a project actually gives you version 1.0.9 of the library?
I was reading your other thread asking for collaborators. The Process explanations says to work on the fix/feature on a separate branch and then doing a pull request. 
For this pull request I worked on the master branch on my fork and then made a pull request. 
Is that fine or does the process change now that I'm a contributor?

**Comment by daimajia** [comment]
@massimobio  Your workflow is also right ( working on your own branch and then send pull request), just make sure that collaborators never push code to master branch. 

I checked the config file again. The version should be v1.1.2, instead of v1.0.9
 https://github.com/daimajia/AndroidImageSlider/blob/master/library/gradle-mvn-push.gradle#L50

**Comment by massimobio** [comment]
@daimajia Is there a way to have the latest commit of the library compile as a dependency in grade while we wait for the next official release?
Or, is the only way to include the library manually into my project?

**Comment by daimajia** [comment]
@massimobio I have successfully push v1.1.2 to maven center. Have a try. :-D

**Pull request merged**
